apiVersion: v1
kind: Service
metadata:
  name: app-web-chat-messages
spec:
  selector:
    app: app-web-chat-messages
  ports:
    - protocol: TCP
      port: 4201
      targetPort: 80
  type: LoadBalancer